ClubeAaano/Controllers/PlanoPagSeguroController.cs
using AaanoBll.Base;
using AaanoBll.ClubeAaano;
using AaanoDto.ClubeAaano;
using AaanoDto.Requisicoes;
using AaanoDto.Retornos;
using ClubeAaanoSite.Models;
using System;
using System.Collections.Generic;
using System.Web.Mvc;
using System.Web.Script.Serialization;

namespace ClubeAaanoSite.Controllers
{
    public class PlanoPagSeguroController : BaseController
    {
        /// <summary>
        /// Chama a tela com a listagem de lojas
        /// </summary>
        /// <returns></returns>
        public ActionResult Index()
        {
            // Se não tiver login, encaminhar para a tela de login
            if (string.IsNullOrWhiteSpace(SessaoUsuario.SessaoLogin.Identificacao))
            {
                return RedirectToAction("Login", "Usuario");
            }

            if (!SessaoUsuario.SessaoLogin.Administrador)
            {
                ViewBag.MensagemErro = "Para consultar as lojas parceiras é necessário " +
                    $"logar com um usuário administrador.";
                return View("SemPermissao");
            }

            //Chamar a view
            return View();
        }

        /// <summary>
        /// Chama a tela para incluir uma loja
        /// </summary>
        /// <returns></returns>
        public ActionResult Incluir()
        {
            //Se não tiver login, encaminhar para a tela de login
            if (string.IsNullOrWhiteSpace(SessaoUsuario.SessaoLogin.Identificacao))
            {
                return RedirectToAction("Login", "Usuario");
            }

            if (!SessaoUsuario.SessaoLogin.Administrador)
            {
                ViewBag.MensagemErro = "Para incluir uma loja parceira é necessário " +
                    $"logar com um usuário administrador.";
                return View("SemPermissao");
            }

            //PlanoPagSeguro a ser incluído
            PlanoPagSeguroModel model = new PlanoPagSeguroModel()
            {
                Id = Guid.NewGuid()
            };

            TempData["Retorno"] = "INCLUINDO";

            //Chamar a view
            return View(model);
        }

        /// <summary>
        /// Consome o serviço para incluir uma nova loja
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Incluir(PlanoPagSeguroModel model)
        {
            //Se não tiver login, encaminhar para a tela de login
            if (string.IsNullOrWhiteSpace(SessaoUsuario.SessaoLogin.Identificacao))
            {
                return RedirectToAction("Login", "Usuario");
            }

            if (!SessaoUsuario.SessaoLogin.Administrador)
            {
                ViewBag.MensagemErro = "Para incluir uma loja parceira é necessário " +
                    $"logar com um usuário administrador.";
                return View("SemPermissao");
            }

            //Validar a model recebida
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            if (model.Id == Guid.Empty || model.Id == null)
            {
                ModelState.AddModelError("Id", "O id do plano é obrigatório.");
                return View(model);
            }

            //Converter para DTO
            PlanoPagSeguroDto planoPagSeguro = new PlanoPagSeguroDto();
            string mensagemErro = "";
            if (!model.ConverterModelParaDto(ref planoPagSeguro, ref mensagemErro))
            {
                ModelState.AddModelError("", $"Erro ao converter para Dto: {mensagemErro}");
                return View(model);
            }

            //Preparar requisição e retorno
            RetornoDto retorno = new RetornoDto();
            RequisicaoEntidadeDto<PlanoPagSeguroDto> requisicaoDto = new RequisicaoEntidadeDto<PlanoPagSeguroDto>()
            {
                EntidadeDto = planoPagSeguro,
                LojasPermitidas = SessaoUsuario.SessaoLogin.LojasPermitidas,
                Identificacao = SessaoUsuario.SessaoLogin.Identificacao,
                IdUsuario = SessaoUsuario.SessaoLogin.IdUsuario
            };

            //Consumir o serviço
            PlanoPagSeguroBll planoPagSeguroBll = new PlanoPagSeguroBll(true);
            planoPagSeguroBll.Incluir(requisicaoDto, ref retorno);

            //Verificar o retorno 
            if (retorno.Retorno == false)
            {
                //Se houver erro, exibir na tela de inclusão
                ModelState.AddModelError("", retorno.Mensagem);
                return View(model);
            }

            TempData["Retorno"] = "INCLUIDO";

            //Retornar para index
            return RedirectToAction("Index");
        }

        /// <summary>
        /// Chama a tela para visualizar uma loja
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public ActionResult Visualizar(Guid id)
        {
            //Se não tiver login, encaminhar para a tela de login
            if (string.IsNullOrWhiteSpace(SessaoUsuario.SessaoLogin.Identificacao))
            {
                return RedirectToAction("Login", "Usuario");
            }

            if (!SessaoUsuario.SessaoLogin.Administrador)
            {
                ViewBag.MensagemErro = "Para visualizar uma loja parceira é necessário " +
                    $"logar com um usuário administrador.";
                return View("SemPermissao");
            }

            //Model a ser populada
            PlanoPagSeguroModel model = new PlanoPagSeguroModel();
            string mensagemRetorno = "";

            //Obtem pelo ID
            if (!this.ObterPlanoPagSeguro(id, ref model, ref mensagemRetorno))
            {
                ViewBag.MensagemErro = mensagemRetorno;
                return View("Erro");
            }

            TempData["Retorno"] = "VISUALIZANDO";

            //Chamar a view
            return View(model);
        }

        /// <summary>
        /// Chama a tela para editar uma loja
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public ActionResult Editar(Guid id)
        {
            //Se não tiver login, encaminhar para a tela de login
            if (string.IsNullOrWhiteSpace(SessaoUsuario.SessaoLogin.Identificacao))
            {
                return RedirectToAction("Login", "Usuario");
            }

            if (!SessaoUsuario.SessaoLogin.Administrador)
            {
                ViewBag.MensagemErro = "Para editar uma loja parceira é necessário " +
                    $"logar com um usuário administrador.";
                return View("SemPermissao");
            }

            //Model a ser populada
            PlanoPagSeguroModel model = new PlanoPagSeguroModel();
            string mensagemRetorno = "";

            //Obtem o pelo ID
            if (!this.ObterPlanoPagSeguro(id, ref model, ref mensagemRetorno))
            {
                ViewBag.MensagemErro = mensagemRetorno;
                return View("Erro");
            }

            TempData["Retorno"] = "EDITANDO";

            //Chamar a view
            return View(model);
        }

        /// <summary>
        /// Consome o serviço para salvar os dados da loja
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Editar(PlanoPagSeguroModel model)
        {
            //Se não tiver login, encaminhar para a tela de login
            if (string.IsNullOrWhiteSpace(SessaoUsuario.SessaoLogin.Identificacao))
            {
                return RedirectToAction("Login", "Usuario");
            }

            if (!SessaoUsuario.SessaoLogin.Administrador)
            {
                ViewBag.MensagemErro = "Para editar uma loja parceira é necessário " +
                    $"logar com um usuário administrador.";
                return View("SemPermissao");
            }

            //Valida a entidade recebida
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            //Converte para DTO
            PlanoPagSeguroDto planoPagSeguroDto = new PlanoPagSeguroDto();
            string mensagemErro = "";
            if (!model.ConverterModelParaDto(ref planoPagSeguroDto, ref mensagemErro))
            {
                ViewBag.MensagemErro = mensagemErro;
                return View("Erro");
            }

            //Preparar requisição e retorno
            RetornoDto retorno = new RetornoDto();
            RequisicaoEntidadeDto<PlanoPagSeguroDto> requisicaoDto = new RequisicaoEntidadeDto<PlanoPagSeguroDto>()
            {
                EntidadeDto = planoPagSeguroDto,
                LojasPermitidas = SessaoUsuario.SessaoLogin.LojasPermitidas,
                Identificacao = SessaoUsuario.SessaoLogin.Identificacao,
                IdUsuario = SessaoUsuario.SessaoLogin.IdUsuario
            };

            //Consumir o serviço
            PlanoPagSeguroBll planoPagSeguroBll = new PlanoPagSeguroBll(true);
            planoPagSeguroBll.Editar(requisicaoDto, ref retorno);

            //Tratar o retorno
            if (retorno.Retorno == false)
            {
                ModelState.AddModelError("", retorno.Mensagem);
                return View(model);
            }

            TempData["Retorno"] = "ALTERADO";

            //Voltar para a index 
            return RedirectToAction("Index");
        }

        /// <summary>
        /// Chama a tela para excluir uma loja
        /// </summary>
        /// <param name="id"></param>

ClubeAaano/Views/PlanoPagSeguro/Editar.cshtml
@model ClubeAaanoSite.Models.PlanoPagSeguroModel

@{
    ViewBag.Title = "Editar plano pagseguro";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="content-wrapper">
    <div class="content-header">
        <h1>
            Plano pagseguro
            <small>Editar</small>
        </h1>
        <ol class="breadcrumb">
            <li><a href="~/Usuario/Inicio"><i class="fa fa-home"></i> Inicio</a></li>
            <li><a href="~/PlanoPagSeguro/Index"><i class="fa fa-male"></i> Planos pagseguro</a></li>
            <li class="active"><i class="fa fa-pencil"></i> Editar</li>
        </ol>
    </div>

    <div class="content">
        <div class="row">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <div class="box box-primary">
                    <div class="box-header with-border">
                        <h2 class="box-title">Editar informações do plano</h2>
                    </div>

                    @using (Html.BeginForm())
                    {
                        <div class="box-body">
                            <div class="form-horizontal">

                                @Html.AntiForgeryToken()
                                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                                @Html.HiddenFor(m => m.Id)

                                <div class="form-group">
                                    @Html.LabelFor(m => m.CodigoSimplificado, new { @class = "control-label col-lg-2 col-md-2 col-sm-3 col-xs-12" })
                                    <div class="col-lg-3 col-md-3 col-sm-4 col-xs-12">
                                        @Html.EditorFor(m => m.CodigoSimplificado, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(m => m.CodigoSimplificado, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="form-group">
                                    @Html.LabelFor(m => m.Nome, new { @class = "control-label col-lg-2 col-md-2 col-sm-3 col-xs-12" })
                                    <div class="col-lg-8 col-md-9 col-sm-9 col-xs-12">
                                        @Html.EditorFor(m => m.Nome, new { htmlAttributes = new { @class = "form-control", @autocomplete = "off" } })
                                        @Html.ValidationMessageFor(m => m.Nome, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="form-group">
                                    @Html.LabelFor(m => m.Id, new { @class = "control-label col-lg-2 col-md-2 col-sm-3 col-xs-12" })
                                    <div class="col-lg-4 col-md-4 col-sm-9 col-xs-12">
                                        @Html.EditorFor(m => m.Id, new { htmlAttributes = new { @class = "form-control", @autocomplete = "off", @readonly = "readonly" } })
                                        @Html.ValidationMessageFor(m => m.Id, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="form-group">
                                    @Html.LabelFor(m => m.DataInclusao, new { @class = "col-lg-3 col-md-3 col-sm-3 col-xs-12 alinhadoDireita small" })
                                    <div class="col-lg-2 col-md-3 col-sm-3 col-xs-12 alinhadoDireita small">
                                        @Html.HiddenFor(m => m.DataInclusao)
                                        @Html.DisplayFor(m => m.DataInclusao, new { @class = "form-control" })
                                        @Html.ValidationMessageFor(m => m.DataInclusao, "", new { @class = "text-danger" })
                                    </div>

                                    @Html.LabelFor(m => m.DataAlteracao, new { @class = "col-lg-4 col-md-3 col-sm-3 col-xs-12 alinhadoDireita small" })
                                    <div class="col-lg-2 col-md-3 col-sm-3 col-xs-12 alinhadoDireita small">
                                        @Html.HiddenFor(m => m.DataAlteracao)
                                        @Html.DisplayFor(m => m.DataAlteracao, new { @class = "form-control" })
                                        @Html.ValidationMessageFor(m => m.DataAlteracao, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="box-footer">
                                    <div class="col-lg-offset-2 col-md-offset-2 col-sm-offset-3">
                                        <a class="btn btn-default" href="~/PlanoPagSeguro/Index"><i class="fa fa-mail-reply"></i> Cancelar</a>
                                        <button type="submit" class="btn btn-primary" data-toggle="modal"><i class="fa fa-save"></i> Gravar</button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
</div>


ClubeAaano/Views/PlanoPagSeguro/Excluir.cshtml
@model ClubeAaanoSite.Models.ExclusaoModel

@{
    ViewBag.Title = "Excluir plano";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="content-wrapper">
    <div class="content-header">
        <h1>
            Planos pagseguro
            <small>Excluir</small>
        </h1>
        <ol class="breadcrumb">
            <li><a href="~/Usuario/Inicio"><i class="fa fa-home"></i> Inicio</a></li>
            <li><a href="~/PlanoPagSeguro/Index"><i class="fa fa-male"></i> Planos pagseguro</a></li>
            <li class="active"><i class="fa fa-trash"></i> Excluir</li>
        </ol>
    </div>

    <div class="content">
        <div class="row">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <div class="box box-primary">
                    <div class="box-header with-border">
                        <h2 class="box-title">Confirme a exclusão do plano</h2>
                    </div>

                    @using (Html.BeginForm("ExcluirPlanoPagSeguro", "PlanoPagSeguro"))
                    {
                        @Html.AntiForgeryToken()

                        <div class="box-body">
                            <div class="form-horizontal">
                                <div class="form-group">
                                    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                                        @Html.HiddenFor(model => model.Id)
                                        @Html.HiddenFor(model => model.Descricao)
                                        <br />
                                        <p>
                                            Tem certeza que deseja excluir a o plano "<b>@Model.Descricao</b>"?
                                        </p>
                                        <h4 class="text-danger">Essa operação não poderá ser desfeita e os dados referentes a ela serão perdidos.</h4>
                                        <br />
                                    </div>
                                </div>

                                <div class="box-footer">
                                    <a class="btn btn-default" href="~/PlanoPagSeguro/Index"><i class="fa fa-mail-reply"></i> Cancelar</a>
                                    <button type="submit" class="btn btn-danger"><i class="fa fa-trash"></i> Excluir</button>
                                </div>
                            </div>
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
</div>

ClubeAaano/Views/PlanoPagSeguro/Incluir.cshtml
@model ClubeAaanoSite.Models.PlanoPagSeguroModel

@{
    ViewBag.Title = "Incluir Plano pagseguro";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="content-wrapper">
    <div class="content-header">
        <h1>
            Plano pagseguro
            <small>Incluir</small>
        </h1>
        <ol class="breadcrumb">
            <li><a href="~/Usuario/Inicio"><i class="fa fa-home"></i> Inicio</a></li>
            <li><a href="~/PlanoPagSeguro/Index"><i class="fa fa-male"></i> Planos pagseguro</a></li>
            <li class="active"><i class="fa fa-plus"></i> Incluir</li>
        </ol>
    </div>

    <div class="content">
        <div class="row">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <div class="box box-primary">

                    <div class="box-header with-border">
                        <h2 class="box-title">Informações do novo plano</h2>
                    </div>

                    @using (Html.BeginForm())
                    {
                        <div class="box-body">
                            <div class="form-horizontal">
                                @Html.AntiForgeryToken()
                                @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                                <div class="form-group">
                                    @Html.LabelFor(m => m.CodigoSimplificado, new { @class = "control-label col-lg-2 col-md-2 col-sm-3 col-xs-12" })
                                    <div class="col-lg-3 col-md-3 col-sm-4 col-xs-12">
                                        @Html.EditorFor(m => m.CodigoSimplificado, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(m => m.CodigoSimplificado, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="form-group">
                                    @Html.LabelFor(m => m.Nome, new { @class = "control-label col-lg-2 col-md-2 col-sm-3 col-xs-12" })
                                    <div class="col-lg-8 col-md-9 col-sm-9 col-xs-12">
                                        @Html.EditorFor(m => m.Nome, new { htmlAttributes = new { @class = "form-control", @autocomplete = "off" } })
                                        @Html.ValidationMessageFor(m => m.Nome, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="form-group">
                                    @Html.LabelFor(m => m.Id, new { @class = "control-label col-lg-2 col-md-2 col-sm-3 col-xs-12" })
                                    <div class="col-lg-4 col-md-4 col-sm-9 col-xs-12">
                                        @Html.EditorFor(m => m.Id, new { htmlAttributes = new { @class = "form-control", @autocomplete = "off" } })
                                        @Html.ValidationMessageFor(m => m.Id, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="box-footer">
                                    <div class="col-lg-offset-2 col-md-offset-2 col-sm-offset-3">
                                        <a class="btn btn-default" href="~/PlanoPagSeguro/Index"><i class="fa fa-mail-reply"></i> Cancelar</a>
                                        <button type="submit" class="btn btn-primary"><i class="fa fa-save"></i> Gravar</button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
</div>

ClubeAaano/Views/PlanoPagSeguro/Index.cshtml
@{
    ViewBag.Title = "Planos Pagseguro";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="content-wrapper">
    <div class="form-horizontal">
        <div class="content-header">
            <h1>
                Planos Pagseguro
                <small>Listagem</small>
            </h1>
            <ol class="breadcrumb">
                <li><a href="~/Usuario/Inicio"><i class="fa fa-home"></i> Inicio</a></li>
                <li><a class="active"><i class="fa fa-male"></i> Planos Pagseguro</a></li>
            </ol>
        </div>

        <div class="content">
            <div class="row">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="box box-primary">
                        <div class="box-header with-border">
                            <h3 class="box-title">Pesquisa de planos do pagseguro</h3>
                        </div>

                        <div class="box-body">
                            <div class="form-group">
                                <label class="control-label col-lg-2 col-md-2 col-sm-3 col-xs-12">Nome</label>
                                <div class="col-lg-9 col-md-10 col-sm-9 col-xs-12">
                                    <input type="text" class="form-control" autocomplete="off" placeholder="Pesquise por nome" id="txtNome">
                                </div>
                            </div>

                            <div class="form-group">
                                <label class="control-label col-lg-2 col-md-2 col-sm-3 col-xs-12">Id</label>
                                <div class="col-lg-6 col-md-7 col-sm-9 col-xs-12">
                                    <input type="text" class="form-control" autocomplete="off" placeholder="Pesquise por ID do plano" id="txtIdPlano">
                                </div>
                            </div>

                            <div class="form-group">
                                <div class="col-lg-offset-2 col-md-offset-2 col-sm-offset-3 col-lg-10 col-md-10 col-sm-9 col-xs-12">
                                    <button class="btn btn-primary" id="btnBuscarPlanos"><i class="fa fa-search"></i> Buscar</button>
                                </div>
                            </div>
                        </div>

                        <div class="overlay" id="divCarregando">
                            <i class="fa fa-refresh fa-spin"></i>
                        </div>
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="box box-primary">
                        <div class="box-header with-border">
                            <div class="form-group">
                                <div class="col-md-6">
                                    <h3 class="box-title">Lista de planos do pagseguro</h3>
                                </div>
                                <div class="col-md-6 alinhadoDireita">
                                    <a class="btn btn-primary" href="Incluir"><i class="fa fa-plus"></i> Novo plano</a>
                                </div>
                            </div>
                        </div>

                        <div class="box-body table-responsive">
                            <table class="table table-hover" id="tblResultados">
                                <thead>
                                    <tr>
                                        <th>Id</th>
                                        <th>Nome</th>
                                        <th>Código</th>
                                        <th>Opções</th>
                                    </tr>
                                </thead>
                                <tbody></tbody>
                            </table>
                        </div>

                        <div class="box-footer clearfix" id="divPaginas">
                            @*Paginação da pesquisa*@
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script src="~/Scripts/ClubeAaanoSite/plugins/jQueryUI/jquery-3.3.1.min.js"></script>
<script src="~/Scripts/ClubeAaanoSite/plugins/jQueryUI/toastr.min.js"></script>
<script src="~/Scripts/ClubeAaanoSite/Telas/Geral.js"></script>
<script src="~/Scripts/ClubeAaanoSite/Telas/IndexPlanoPagSeguro.js"></script>

<script>
    $(document).ready(function () {
        var retorno = '@TempData["Retorno"]';
        MostrarMensagemRetorno(retorno, "O plano");
        BuscarPlanos(1);

        $("#btnBuscarPlanos").click(function () {
            BuscarPlanos(1);
        });

        $(document).keypress(function (e) {
            if (e.keyCode === 13) {
                $("#btnBuscarPlanos").click();
            }
        });
    });
</script>