ClubeAaano/Controllers/BrindeController.cs
using AaanoBll.ClubeAaano;
using AaanoDto.ClubeAaano;
using AaanoDto.Requisicoes;
using AaanoDto.Retornos;
using ClubeAaanoSite.Models;
using System;
using System.Web.Mvc;
using System.Web.Script.Serialization;

namespace ClubeAaanoSite.Controllers
{
    public class BrindeController : BaseController
    {
        /// <summary>
        /// Chama a tela com a listagem de brindes
        /// </summary>
        /// <returns></returns>
        public ActionResult Index()
        {
            // Se não tiver login, encaminhar para a tela de login
            if (string.IsNullOrWhiteSpace(SessaoUsuario.SessaoLogin.Identificacao))
            {
                return RedirectToAction("Login", "Usuario");
            }

            if (!SessaoUsuario.SessaoLogin.Administrador)
            {
                ViewBag.MensagemErro = "Para consultar os brindes é necessário " +
                    $"logar com um usuário administrador.";
                return View("SemPermissao");
            }

            PesquisaInicialModel model = new PesquisaInicialModel();

            //Chamar a view
            return View(model);
        }

        /// <summary>
        /// Chama a tela para incluir um brinde
        /// </summary>
        /// <returns></returns>
        public ActionResult Incluir()
        {
            //Se não tiver login, encaminhar para a tela de login
            if (string.IsNullOrWhiteSpace(SessaoUsuario.SessaoLogin.Identificacao))
            {
                return RedirectToAction("Login", "Usuario");
            }

            if (!SessaoUsuario.SessaoLogin.Administrador)
            {
                ViewBag.MensagemErro = "Para incluir um brinde é necessário " +
                    $"logar com um usuário administrador.";
                return View("SemPermissao");
            }

            //Brinde a ser incluído
            BrindeModel model = new BrindeModel()
            {
                Id = Guid.NewGuid()
            };

            TempData["Retorno"] = "INCLUINDO";

            //Chamar a view
            return View(model);
        }

        /// <summary>
        /// Consome o serviço para incluir um brinde
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Incluir(BrindeModel model)
        {
            //Se não tiver login, encaminhar para a tela de login
            if (string.IsNullOrWhiteSpace(SessaoUsuario.SessaoLogin.Identificacao))
            {
                return RedirectToAction("Login", "Usuario");
            }

            if (!SessaoUsuario.SessaoLogin.Administrador)
            {
                ViewBag.MensagemErro = "Para incluir um brinde é necessário " +
                    $"logar com um usuário administrador.";
                return View("SemPermissao");
            }

            //Validar a model recebida
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            //Converter para DTO
            BrindeDto brinde = new BrindeDto();
            string mensagemErro = "";
            if (!model.ConverterModelParaDto(ref brinde, ref mensagemErro))
            {
                ModelState.AddModelError("", $"Erro ao converter para Dto: {mensagemErro}");
                return View(model);
            }

            brinde.Id = Guid.NewGuid();

            //Preparar requisição e retorno
            RetornoDto retorno = new RetornoDto();
            RequisicaoEntidadeDto<BrindeDto> requisicaoDto = new RequisicaoEntidadeDto<BrindeDto>()
            {
                EntidadeDto = brinde,
                LojasPermitidas = SessaoUsuario.SessaoLogin.LojasPermitidas,
                Identificacao = SessaoUsuario.SessaoLogin.Identificacao,
                IdUsuario = SessaoUsuario.SessaoLogin.IdUsuario
            };

            //Consumir o serviço
            BrindeBll brindeBll = new BrindeBll(true);
            brindeBll.Incluir(requisicaoDto, ref retorno);

            //Verificar o retorno 
            if (retorno.Retorno == false)
            {
                //Se houver erro, exibir na tela de inclusão
                ModelState.AddModelError("", retorno.Mensagem);
                return View(model);
            }

            TempData["Retorno"] = "INCLUIDO";

            //Retornar para index
            return RedirectToAction("Index");
        }

        /// <summary>
        /// Chama a tela para visualizar um brinde
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public ActionResult Visualizar(Guid id)
        {
            //Se não tiver login, encaminhar para a tela de login
            if (string.IsNullOrWhiteSpace(SessaoUsuario.SessaoLogin.Identificacao))
            {
                return RedirectToAction("Login", "Usuario");
            }

            if (!SessaoUsuario.SessaoLogin.Administrador)
            {
                ViewBag.MensagemErro = "Para visualizar um brinde é necessário " +
                    $"logar com um usuário administrador.";
                return View("SemPermissao");
            }

            //Model a ser populada
            BrindeModel model = new BrindeModel();
            string mensagemRetorno = "";

            //Obtem pelo ID
            if (!this.ObterBrinde(id, ref model, ref mensagemRetorno))
            {
                ViewBag.MensagemErro = mensagemRetorno;
                return View("Erro");
            }

            TempData["Retorno"] = "VISUALIZANDO";

            //Chamar a view
            return View(model);
        }

        /// <summary>
        /// Chama a tela para editar um brinde
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public ActionResult Editar(Guid id)
        {
            //Se não tiver login, encaminhar para a tela de login
            if (string.IsNullOrWhiteSpace(SessaoUsuario.SessaoLogin.Identificacao))
            {
                return RedirectToAction("Login", "Usuario");
            }

            if (!SessaoUsuario.SessaoLogin.Administrador)
            {
                ViewBag.MensagemErro = "Para editar um brinde é necessário " +
                    $"logar com um usuário administrador.";
                return View("SemPermissao");
            }

            //Model a ser populada
            BrindeModel model = new BrindeModel();
            string mensagemRetorno = "";

            //Obtem o pelo ID
            if (!this.ObterBrinde(id, ref model, ref mensagemRetorno))
            {
                ViewBag.MensagemErro = mensagemRetorno;
                return View("Erro");
            }

            TempData["Retorno"] = "EDITANDO";

            //Chamar a view
            return View(model);
        }

        /// <summary>
        /// Consome o serviço para salvar a brinde
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Editar(BrindeModel model)
        {
            //Se não tiver login, encaminhar para a tela de login
            if (string.IsNullOrWhiteSpace(SessaoUsuario.SessaoLogin.Identificacao))
            {
                return RedirectToAction("Login", "Usuario");
            }

            if (!SessaoUsuario.SessaoLogin.Administrador)
            {
                ViewBag.MensagemErro = "Para editar um brinde é necessário " +
                    $"logar com um usuário administrador.";
                return View("SemPermissao");
            }

            //Valida a entidade recebida
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            //Converte para DTO
            BrindeDto brindeDto = new BrindeDto();
            string mensagemErro = "";
            if (!model.ConverterModelParaDto(ref brindeDto, ref mensagemErro))
            {
                ViewBag.MensagemErro = mensagemErro;
                return View("Erro");
            }

            //Preparar requisição e retorno
            RetornoDto retorno = new RetornoDto();
            RequisicaoEntidadeDto<BrindeDto> requisicaoDto = new RequisicaoEntidadeDto<BrindeDto>()
            {
                EntidadeDto = brindeDto,
                LojasPermitidas = SessaoUsuario.SessaoLogin.LojasPermitidas,
                Identificacao = SessaoUsuario.SessaoLogin.Identificacao,
                IdUsuario = SessaoUsuario.SessaoLogin.IdUsuario
            };

            //Consumir o serviço
            BrindeBll brindeBll = new BrindeBll(true);
            brindeBll.Editar(requisicaoDto, ref retorno);

            //Tratar o retorno
            if (retorno.Retorno == false)
            {
                ModelState.AddModelError("", retorno.Mensagem);
                return View(model);
            }

            TempData["Retorno"] = "ALTERADO";

            //Voltar para a index 
            return RedirectToAction("Index");
        }

        /// <summary>
        /// Chama a tela para excluir um brinde
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public ActionResult Excluir(ExclusaoModel model)
        {
            //Se não tiver login, encaminhar para a tela de login
            if (string.IsNullOrWhiteSpace(SessaoUsuario.SessaoLogin.Identificacao))
            {
                return RedirectToAction("Login", "Usuario");
            }

            if (!SessaoUsuario.SessaoLogin.Administrador)
            {

ClubeAaano/Views/Brinde/Editar.cshtml
@model ClubeAaanoSite.Models.BrindeModel

@{
    ViewBag.Title = "Editar brinde";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="content-wrapper">
    <div class="content-header">
        <h1>
            Brinde
            <small>Editar</small>
        </h1>
        <ol class="breadcrumb">
            <li><a href="~/Usuario/Inicio"><i class="fa fa-home"></i> Inicio</a></li>
            <li><a href="~/LojaParcela/Index"><i class="fa fa-gift"></i> Brindes</a></li>
            <li class="active"><i class="fa fa-pencil"></i> Editar</li>
        </ol>
    </div>

    <div class="content">
        <div class="row">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <div class="box box-primary">
                    <div class="box-header with-border">
                        <h2 class="box-title">Editar informações do brinde</h2>
                    </div>

                    @using (Html.BeginForm())
                    {
                        <div class="box-body">
                            <div class="form-horizontal">

                                @Html.AntiForgeryToken()
                                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                                @Html.HiddenFor(m => m.Id)

                                <div class="form-group">
                                    @Html.LabelFor(m => m.Descricao, new { @class = "control-label col-lg-2 col-md-2 col-sm-3 col-xs-12" })
                                    <div class="col-lg-8 col-md-9 col-sm-9 col-xs-12">
                                        @Html.EditorFor(m => m.Descricao, new { htmlAttributes = new { @class = "form-control", @autocomplete = "off" } })
                                        @Html.ValidationMessageFor(m => m.Descricao, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="form-group">
                                    @Html.LabelFor(m => m.Sorteio, new { @class = "control-label col-lg-2 col-md-2 col-sm-3 col-xs-12" })
                                    <div class="col-lg-3 col-md-4 col-sm-9 col-xs-12">
                                        @Html.EditorFor(m => m.Sorteio, new { htmlAttributes = new { @class = "form-control", @autocomplete = "off" } })
                                        @Html.ValidationMessageFor(m => m.Sorteio, "", new { @class = "text-danger" })
                                    </div>

                                    @Html.LabelFor(m => m.Entregue, new { @class = "control-label col-lg-2 col-md-2 col-sm-3 col-xs-12" })
                                    <div class="col-lg-1 col-md-1 col-sm-2 col-xs-2">
                                        @Html.EditorFor(m => m.Entregue, new { htmlAttributes = new { @class = "checkbox", @style = "margin-top:5px" } })
                                        @Html.ValidationMessageFor(m => m.Entregue, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                @Html.Partial("_SelecionarAssinatura")

                                <div class="form-group">
                                    @Html.LabelFor(m => m.NomeAssinante, new { @class = "control-label col-lg-2 col-md-2 col-sm-3 col-xs-12" })
                                    <div class="col-lg-8 col-md-9 col-sm-9 col-xs-12">
                                        <div class="input-group">
                                            @Html.HiddenFor(m => m.IdAssinaturaPagSeguro)
                                            @Html.EditorFor(m => m.NomeAssinante, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                                            @Html.ValidationMessageFor(m => m.NomeAssinante, "", new { @class = "text-danger" })

                                            <div class="input-group-btn">
                                                @if (Model.IdAssinaturaPagSeguro != null && Model.IdAssinaturaPagSeguro != Guid.Empty)
                                                {
                                                    <button id="btnBuscarAssinatura" type="button" class="btn btn-primary"><i class="fa fa-eraser"></i> Limpar</button>
                                                }
                                                else
                                                {
                                                    <button id="btnBuscarAssinatura" type="button" class="btn btn-primary"><i class="fa fa-search"></i> Pesquisar</button>
                                                }
                                            </div>
                                        </div>
                                    </div>
                                </div>

                                <div class="form-group">
                                    @Html.LabelFor(m => m.DataInclusao, new { @class = "col-lg-3 col-md-3 col-sm-3 col-xs-12 alinhadoDireita small" })
                                    <div class="col-lg-2 col-md-3 col-sm-3 col-xs-12 alinhadoDireita small">
                                        @Html.HiddenFor(m => m.DataInclusao)
                                        @Html.DisplayFor(m => m.DataInclusao, new { @class = "form-control" })
                                        @Html.ValidationMessageFor(m => m.DataInclusao, "", new { @class = "text-danger" })
                                    </div>

                                    @Html.LabelFor(m => m.DataAlteracao, new { @class = "col-lg-4 col-md-3 col-sm-3 col-xs-12 alinhadoDireita small" })
                                    <div class="col-lg-2 col-md-3 col-sm-3 col-xs-12 alinhadoDireita small">
                                        @Html.HiddenFor(m => m.DataAlteracao)
                                        @Html.DisplayFor(m => m.DataAlteracao, new { @class = "form-control" })
                                        @Html.ValidationMessageFor(m => m.DataAlteracao, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="box-footer">
                                    <div class="col-lg-offset-2 col-md-offset-2 col-sm-offset-3">
                                        <a class="btn btn-default" href="~/Brinde/Index"><i class="fa fa-mail-reply"></i> Cancelar</a>
                                        <button type="submit" class="btn btn-primary" data-toggle="modal"><i class="fa fa-save"></i> Gravar</button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
</div>

<script src="~/Scripts/ClubeAaanoSite/plugins/mask/jquery.mask.min.js"></script>
<script src="~/Scripts/ClubeAaanoSite/Telas/Geral.js"></script>

<script>
    $(document).ready(function () {
        $("#Sorteio").mask("99/99/9999", { placeholder: "__/__/____" });

        $("#btnBuscarAssinatura").click(function () {
            if ($("#btnBuscarAssinatura").html().indexOf("Limpar") !== -1) {
                $("#IdAssinaturaPagSeguro").val("");
                $("#NomeAssinante").val("");
                $("#btnBuscarAssinatura").html("<i class='fa fa-search'></i> Pesquisar");
            } else {
                ExibirModelPesquisaAssinatura();
            }
        });

        $(document).keypress(function (e) {
            var keycode = (e.keyCode ? e.keyCode : e.which);
            if (keycode === 13 || keycode === '13') {
                return false;
                e.preventDefault();
            }
        });
    });

    // Ao selecionar uma promoção para filtrar
    function SelecionarAssinatura(codigo, nome, id) {
        $("#IdAssinaturaPagSeguro").val(id);
        $("#NomeAssinante").val(nome);
        $("#btnBuscarAssinatura").html("<i class='fa fa-eraser'></i> Limpar");
        $("#modalSelecionarAssinatura").modal("hide");
    }
</script>

ClubeAaano/Views/Brinde/Excluir.cshtml
@model ClubeAaanoSite.Models.ExclusaoModel

@{
    ViewBag.Title = "Excluir brinde";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="content-wrapper">
    <div class="content-header">
        <h1>
            Brindes
            <small>Excluir</small>
        </h1>
        <ol class="breadcrumb">
            <li><a href="~/Usuario/Inicio"><i class="fa fa-home"></i> Inicio</a></li>
            <li><a href="~/Brinde/Index"><i class="fa fa-gift"></i> Brindes</a></li>
            <li class="active"><i class="fa fa-trash"></i> Excluir</li>
        </ol>
    </div>

    <div class="content">
        <div class="row">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <div class="box box-primary">
                    <div class="box-header with-border">
                        <h2 class="box-title">Confirme a exclusão da brinde</h2>
                    </div>

                    @using (Html.BeginForm("ExcluirBrinde", "Brinde"))
                    {
                        @Html.AntiForgeryToken()

                        <div class="box-body">
                            <div class="form-horizontal">
                                <div class="form-group">
                                    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                                        @Html.HiddenFor(model => model.Id)
                                        @Html.HiddenFor(model => model.Descricao)
                                        <br />
                                        <p>
                                            Tem certeza que deseja excluir o brinde "<b>@Model.Descricao</b>"?
                                        </p>
                                        <h4 class="text-danger">Essa operação não poderá ser desfeita e os dados referentes a ela serão perdidos.</h4>
                                        <br />
                                    </div>
                                </div>

                                <div class="box-footer">
                                    <a class="btn btn-default" href="~/Brinde/Index"><i class="fa fa-mail-reply"></i> Cancelar</a>
                                    <button type="submit" class="btn btn-danger"><i class="fa fa-trash"></i> Excluir</button>
                                </div>
                            </div>
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
</div>

ClubeAaano/Views/Brinde/Sortear.cshtml
@model ClubeAaanoSite.Models.BrindeModel

@{
    ViewBag.Title = "Sortear brinde";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="content-wrapper">
    <div class="content-header">
        <h1>
            Brindes
            <small>Sortear</small>
        </h1>
        <ol class="breadcrumb">
            <li><a href="~/Usuario/Inicio"><i class="fa fa-home"></i> Inicio</a></li>
            <li><a href="~/Brinde/Index"><i class="fa fa-gift"></i> Brindes</a></li>
            <li class="active"><i class="fa fa-trophy"></i> Sortear</li>
        </ol>
    </div>

    <div class="content">
        <div class="row">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <div class="box box-primary">
                    <div class="box-header with-border">
                        <h2 class="box-title">Sorteio de brinde</h2>
                    </div>

                    @using (Html.BeginForm("Sortear", "Brinde", FormMethod.Post))
                    {
                        <div class="box-body">
                            <div class="form-horizontal">

                                <div class="form-group">
                                    @Html.LabelFor(m => m.Descricao, new { @class = "control-label col-lg-2 col-md-2 col-sm-3 col-xs-12" })
                                    <div class="col-lg-8 col-md-9 col-sm-9 col-xs-12">
                                        @Html.EditorFor(m => m.Descricao, new { htmlAttributes = new { @class = "form-control", @autocomplete = "off" } })
                                        @Html.ValidationMessageFor(m => m.Descricao, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                @Html.AntiForgeryToken()
                                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                                @Html.HiddenFor(m => m.Id)
                                @Html.HiddenFor(m => m.IdAssinaturaPagSeguro)

                                <div class="form-group">
                                    @Html.LabelFor(m => m.Sorteio, new { @class = "control-label col-lg-2 col-md-2 col-sm-3 col-xs-12" })
                                    <div class="col-lg-3 col-md-4 col-sm-9 col-xs-12">
                                        @Html.EditorFor(m => m.Sorteio, new { htmlAttributes = new { @class = "form-control", @autocomplete = "off" } })
                                        @Html.ValidationMessageFor(m => m.Sorteio, "", new { @class = "text-danger" })
                                    </div>

                                    <div class="col-lg-2 col-md-2 col-sm-2 col-xs-12">
                                        <button class="btn btn-primary" type="button" id="btnSortear"><i class="fa fa-trophy"></i> Iniciar</button>
                                    </div>
                                </div>

                                <div class="form-group">
                                    <div id="divSorteio">
                                        <div class="col-lg-offset-2 col-md-offset-2 col-lg-8 col-md-9 col-sm-9 col-xs-12">
                                            <h3 class="text-danger" id="txtNomeSorteio">Clique para iniciar</h3>
                                        </div>
                                    </div>
                                </div>

                                <div class="box-footer">
                                    <div class="col-lg-offset-2 col-md-offset-2 col-sm-offset-3">
                                        <a class="btn btn-default" href="~/Brinde/Index"><i class="fa fa-mail-reply"></i> Cancelar</a>
                                        <button type="submit" class="btn btn-primary" disabled="disabled" id="btnGravar"><i class="fa fa-save"></i> Gravar</button>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="overlay" id="divCarregando">
                            <i class="fa fa-refresh fa-spin"></i>
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
</div>

<script src="~/Scripts/ClubeAaanoSite/plugins/mask/jquery.mask.min.js"></script>
<script src="~/Scripts/ClubeAaanoSite/Telas/Geral.js"></script>
<script src="~/Scripts/ClubeAaanoSite/Telas/SorteioBrinde.js"></script>

<script>
    $(document).ready(function () {
        $("#Sorteio").mask("99/99/9999", { placeholder: "__/__/____" });
        ObterAssinaturasAtivas();

        $("#btnSortear").click(Sortear);


        $(document).keypress(function (e) {
            var keycode = (e.keyCode ? e.keyCode : e.which);
            if (keycode === 13 || keycode === '13') {
                return false;
                e.preventDefault();
            }
        });
    });
</script>